### ISSUE TITLE
excessive CPU usage during fake auth. and injection

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#644]
**Reported by zack on 22 Jun 2009 17:46 UTC**

Fake auth. and injection in conjunction with airodump-ng results in excessive CPU utilization.

Here are 2 screenshots:

1. This one shows draining the cpu during fake auth. with normal parameters: -1 0 -a xxx mon0 (hihgcpu.png) 

2. That one shows aireplay-ng injecting and airodump-ng collecting (cpufake.png)

Facts:
  * P4 mobile cpu
  * kernel 2.6.28-13 /ubuntu 9/
  * fedora 11 kernel .29
  * on both gnome and kde
  * lastest svn of aircrack-ng
  * issue with b43, zd1211rw and rtl8187

**Comment by aircrack-ng** [comment]
**Modified by misterx on 22 Jun 2009 17:46 UTC**

**Comment by aircrack-ng** [comment]
**Comment by Jano on 22 Jun 2009 17:46 UTC**

For me work without problems.

Tested with:

Ubuntu 8.04 32 bit (Kernel 2.24.24)

Ubuntu 9.04 32 bit (Kernel 2.6.28)

Alfa + aircrack-ng/aircrack-ng@


Bye Jano

**Comment by aircrack-ng** [comment]
**Comment by Zack on 22 Jun 2009 17:46 UTC**

RC1 could not compile on Ubuntu 9.04 so I compiled RC2 of aircrack-ng -- the results are the same. Excessive CPU drainage. If there's a bug in the code, it surely dates from much older versions.

Let me know if I can be of some further assistance.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 22 Jun 2009 17:46 UTC**

What are the compilation errors of rc1 on ubuntu 9.04? I'm nearly sure they are easy to fix.

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 22 Jun 2009 17:46 UTC**

Replying to [misterx](comment:4):
> What are the compilation errors of rc1 on ubuntu 9.04? I'm nearly sure they are easy to fix.

Here it is:


```
cc1: warnings being treated as errors
linux.c: In function is_ndiswrapper:
linux.c:164: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_rate:
linux.c:355: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_channel:
linux.c:729: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:751: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:767: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_freq:
linux.c:820: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function set_monitor:
linux.c:941: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:961: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:980: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:997: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1035: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1043: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1051: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function do_linux_open:
linux.c:1425: error: ignoring return value of system, declared with attribute warn_unused_result
linux.c:1474: error: ignoring return value of system, declared with attribute warn_unused_result
linux.c:1495: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1521: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1539: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1553: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1598: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1627: error: ignoring return value of fgets, declared with attribute warn_unused_result
make[*** [linux.o](3]:) Error 1
make[Leaving directory `/home/zack/aircrack-ng-1.0-rc1/src/osdep'
make[2](3]:): *** [Error 2
make[2](all]): Leaving directory `/home/zack/aircrack-ng-1.0-rc1/src/osdep'
make[*** [osd](1]:) Error 2
make[Leaving directory `/home/Music/aircrack-ng-1.0-rc1/src'
make: *** [all](1]:) Error 2
```

**Comment by aircrack-ng** [comment]
**Modified by misterx on 22 Jun 2009 17:46 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 22 Jun 2009 17:46 UTC**
