### ISSUE TITLE
Fix SSE2 compilation

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1671]
**Reported by misterx on 15 Feb 2016 00:40 UTC**

when turning on the ```SSEFLAG``` in common.cfg (SSEFLAG, INTEL_ASM, PTHREAD), it fails with the following error on Cygwin (32 bit; works fine on 64 bit):
```
$ make sqlite=true pcre=true experimental=true pcre=true
make -C src all
make[Entering directory '/home/Thomas/aircrack-ng-1.2-rc4-win/src'
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o aircrack-ng.o aircrack-ng.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o cpuid.o cpuid.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o crypto.o crypto.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o common.o common.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o sse-intrinsics.o sse-intrinsics.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o memory.o memory.c
gcc -g -W -Wall -O3  -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DHAVE_SQLITE  -DHAVE_PCRE -DCYGWIN -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o wpapsk.o wpapsk.c
wpapsk.c: In function wpapsk_sse:
wpapsk.c:229:35: error: MMX_COEF undeclared (first use in this function)
    ((unsigned int *)sse_hash1)[15*MMX_COEF + (index&(MMX_COEF-1)) + (index>>(MMX_COEF>>1))*SHA_BUF_SIZ*MMX_COEF](1]:) = (84<<3); // all encrypts are 64+20 bytes.
                                   ^
wpapsk.c:229:35: note: each undeclared identifier is reported only once for each function it appears in
wpapsk.c:229:92: error: SHA_BUF_SIZ undeclared (first use in this function)
    ((unsigned int *)sse_hash1)[+ (index&(MMX_COEF-1)) + (index>>(MMX_COEF>>1))*SHA_BUF_SIZ*MMX_COEF](15*MMX_COEF) = (84<<3); // all encrypts are 64+20 bytes.
                                                                                            ^
wpapsk.c:116:23: warning: implicit declaration of function SSESHA1body [#define SIMDSHA1body  SSESHA1body
                       ^
wpapsk.c:340:4: note: in expansion of macro SIMDSHA1body
    SIMDSHA1body((unsigned int*)t_sse_hash1, (unsigned int*)t_sse_hash1, (unsigned int*)t_sse_crypt1, SSEi_MIXED_IN|SSEi_RELOAD|SSEi_OUTPUT_AS_INP_FMT);
    ^
<builtin>: recipe for target 'wpapsk.o' failed
make[1](-Wimplicit-function-declaration]
): *** [Error 1
make[1](wpapsk.o]): Leaving directory '/home/Thomas/aircrack-ng-1.2-rc4-win/src'
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 15 Feb 2016 00:40 UTC**

I'm testing using current trunk and I can't reproduce.

What's the output of ```cat /proc/cpuinfo```. Could you also show the exact content of common.cfg?

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 15 Feb 2016 00:40 UTC**

I got the same error and my common.cfg is:

  INTEL_ASM=Y

  PTHREAD=Y

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 15 Feb 2016 00:40 UTC**

I confirm the same error. Trying to build on Slackware linux 14.2 32bit. Both 1.2-rc4 and latest trunk fails. 
Cpuinfo:

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU N270   @ 1.60GHz
stepping	: 2
microcode	: 0x212
cpu MHz		: 1599.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx constant_tsc arch_perfmon pebs bts aperfmperf eagerfpu pni dtes64 monitor ds_cpl est tm2 ssse3 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3201.23
clflush size	: 64
cache_alignment	: 64
address sizes	: 32 bits physical, 32 bits virtual
power management:

```
gcc 5.3.0 was used to compile.\\

Edit: \\

CFLAGS=-msse2 make\\

fixes my problem!

**Comment by aircrack-ng** [comment]
**Comment by misterx on 15 Feb 2016 00:40 UTC**

Should be fixed by aircrack-ng/aircrack-ng@4472d7dec98133e6f0df336457f2caf1c73d9842.
