### ISSUE TITLE
Cannot compile rtl8180-sa2400 on kernel 2.6.23

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#374]
**Reported by misterx on 17 Jan 2008 21:57 UTC**

compiling rtl8180 (done by airdriver-ng) fails on 2.6.23:
```
/usr/src/drivers/rtl8180-0.21/ieee80211_rx.c: In function ieee80211_monitor_rx:
/usr/src/drivers/rtl8180-0.21/ieee80211_rx.c:296: error: struct sk_buff has no member named mac
/usr/src/drivers/rtl8180-0.21/ieee80211_rx.c: In function ieee80211_r8180_rx:
/usr/src/drivers/rtl8180-0.21/ieee80211_rx.c:1131: error: struct sk_buff has no member named mac
/usr/src/drivers/rtl8180-0.21/ieee80211_rx.c:1131: error: struct sk_buff has no member named nh
```

**Comment by aircrack-ng** [comment]
**Comment by leonkingofthelion on 17 Jan 2008 21:57 UTC**

Also doesn't work with 2.6.22! I'm guess I'm going have to use the windows drivers (wildtanget) to test my network

**Comment by aircrack-ng** [comment]
**Comment by leonkingofthelion on 17 Jan 2008 21:57 UTC**

Just use the latest version of BackTrack (bt3)! It has been compiled on the newest kernel that also works with the drivers. T is also a live cd.

**Comment by aircrack-ng** [comment]
**Modified by misterx on 17 Jan 2008 21:57 UTC**

**Comment by aircrack-ng** [comment]
**Comment by misterx on 17 Jan 2008 21:57 UTC**

Milestone N/A deleted
