### ISSUE TITLE
Aircrack-ng svn trunk doesn't compile on FreeBSD 6.2

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#169]
**Reported by misterx on 16 Apr 2007 20:55 UTC**

Here is the compilation log on a FreeBSD 6.2:

```
[/tmp/0.9](user@alpha)# svn update
At revision 297.
[/tmp/0.9](user@alpha)# make
make -C src all
make -C osdep
Building for FreeBSD
gcc -O -pipe -march=pentium4 -D_FILE_OFFSET_BITS=64 -D_REVISION=`../../evalrev` -fPIC -I.. -c osdep.c
gcc -O -pipe -march=pentium4 -D_FILE_OFFSET_BITS=64 -D_REVISION=`../../evalrev` -fPIC -I.. -c freebsd.c
freebsd.c:41: error: field `pf_txparams' has incomplete type
freebsd.c: In function `fbsd_open':
freebsd.c:325: error: `IEEE80211_BPF_VERSION' undeclared (first use in this function)
freebsd.c:325: error: (Each undeclared identifier is reported only once
freebsd.c:325: error: for each function it appears in.)
freebsd.c:326: error: invalid application of `sizeof' to incomplete type `ieee80211_bpf_params'
freebsd.c:329: error: `IEEE80211_BPF_NOACK' undeclared (first use in this function)
*** Error code 1
 
Stop in /tmp/0.9/src/osdep.
*** Error code 1
 
Stop in /tmp/0.9/src/osdep.
*** Error code 1

Stop in /tmp/0.9/src.
*** Error code 1
 
Stop in /tmp/0.9.
```

**Comment by aircrack-ng** [comment]
**Modified by misterx on 16 Apr 2007 20:55 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 16 Apr 2007 20:55 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 16 Apr 2007 20:55 UTC**

**Comment by aircrack-ng** [comment]
**Modified by misterx on 16 Apr 2007 20:55 UTC**

**Comment by aircrack-ng** [comment]
**Comment by misterx on 16 Apr 2007 20:55 UTC**

FreeBSD 6.2 is too old. Let me know if it doesn't work on the current FreeBSD version.
