### ISSUE TITLE
Undefined symbols _shasse2_cpuid _shasse2_data _shasse2_ends _shasse2_init

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1655]
**Reported by ryandesign on 16 Dec 2015 04:06 UTC**

Hello, I'm the maintainer of aircrack-ng in MacPorts. aircrack-ng 1.2-rc3 does not build on OS X 10.11.2 with Xcode 7.1.1 on a MacBook Pro with 2.6 GHz Intel Core i7 processor. The error is:

```
Undefined symbols for architecture x86_64:
  "_shasse2_cpuid", referenced from:
      _crack_wpa_thread in aircrack-ng.o
      _main in aircrack-ng.o
  "_shasse2_data", referenced from:
      _calc_4pmk in aircrack-ng.o
  "_shasse2_ends", referenced from:
      _calc_4pmk in aircrack-ng.o
  "_shasse2_init", referenced from:
      _calc_4pmk in aircrack-ng.o
ld: symbol(s) not found for architecture x86_64
```

This has been a problem since aircrack-ng 1.0. The MacPorts project has been using these patches to work around the problem:

* [patch-src-aircrack-ng.c.diff](https://trac.macports.org/browser/trunk/dports/security/aircrack-ng/files/patch-src-aircrack-ng.c.diff?rev=135992)
* [patch-src-common.h.diff](https://trac.macports.org/browser/trunk/dports/security/aircrack-ng/files/patch-src-common.h.diff?rev=133700)
* [patch-src-sha1-sse2.h.diff](https://trac.macports.org/browser/trunk/dports/security/aircrack-ng/files/patch-src-sha1-sse2.h.diff?rev=135992)

This is probably not the best solution, since it probably disables assembly code in favor of slower code, but at least it allows it to compile. Perhaps you can come up with a better solution.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 16 Dec 2015 04:06 UTC**

Could you test again with aircrack-ng/aircrack-ng@37af2dfcccedf667e4a8747ee897ac9d9269b1e9 and let me know if it fixes your issue?

**Comment by aircrack-ng** [comment]
**Comment by misterx on 16 Dec 2015 04:06 UTC**

No answer here and no answer over email, so I guess it works. If it doesn't, reopen.

**Comment by aircrack-ng** [comment]
**Comment by ryandesign on 16 Dec 2015 04:06 UTC**

Yes, thank you, 1.2-rc4 builds on macOS Sierra without the above patches.
