### ISSUE TITLE
Fails to compile with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1711]
**Reported by misterx on 20 Dec 2016 18:33 UTC**

Tested using Kali 2016.2, with OpenSSL 1.1.0c, compilation fails with the following message:

```
root@kali:~/aircrack-ng-trunk# make
make -C src all
make[Entering directory '/root/aircrack-ng-trunk/src'
gcc -g -W -Wall -O3  -mavx2 -DJOHN_AVX2 -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=2881  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude -DSIMD_CORE   -c -o aircrack-ng.o aircrack-ng.c
gcc -g -W -Wall -O3  -mavx2 -DJOHN_AVX2 -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=2881  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude -DSIMD_CORE   -c -o cpuid.o cpuid.c
gcc -g -W -Wall -O3  -mavx2 -DJOHN_AVX2 -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=2881  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude -DSIMD_CORE   -c -o crypto.o crypto.c
crypto.c: In function calc_mic:
crypto.c:291:11: error: storage size of ctx isnt known
  HMAC_CTX ctx;
           ^~~
crypto.c:317:2: warning: implicit declaration of function HMAC_CTX_init [-Wimplicit-function-declaration](1]:)
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
crypto.c:327:2: warning: implicit declaration of function HMAC_CTX_cleanup [ HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
crypto.c:291:11: warning: unused variable ctx [-Wunused-variable](-Wimplicit-function-declaration]
)
  HMAC_CTX ctx;
           ^~~
<builtin>: recipe for target 'crypto.o' failed
make[*** [crypto.o](1]:) Error 1
make[Leaving directory '/root/aircrack-ng-trunk/src'
Makefile:25: recipe for target 'all' failed
make: *** [all](1]:) Error 2
```

When switching to libssl1.0-dev, it compiles just fine.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 20 Dec 2016 18:33 UTC**

If solution cannot be easily found, HostAPd 2.6 had to port their code to OpenSSL 1.1, so looking through code changes might help.

For example, those 2 commits:
- https://w1.fi/cgit/hostap/commit/?id=36478a16e622059b71337570e089f932e299358b
- https://w1.fi/cgit/hostap/commit/?id=03e3ddf84e97f193efedd88a380cfcedfff89587

**Comment by aircrack-ng** [comment]
**Comment by misterx on 20 Dec 2016 18:33 UTC**

https://www.openssl.org/docs/man1.1.0/crypto/HMAC.html

**Comment by aircrack-ng** [comment]
**Comment by misterx on 20 Dec 2016 18:33 UTC**

Modifications might need to be done in ```src/gcrypt-openssl-wrapper.h``` too.

**Comment by aircrack-ng** [comment]
**Comment by misterx on 20 Dec 2016 18:33 UTC**

Fixed in #2882.

No modifications needed for ```src/gcrypt-openssl-wrapper.h```
