### ISSUE TITLE
couldnt compile on ubuntu

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#559]
**Reported by d bitmus on 16 Dec 2008 06:33 UTC**

following error occured when compile on ubuntu 8.10 desktop

ea@nbea:~/Desktop/aircrack-ng-1.0-rc1$ make
make -C src all
make[Entering directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src'
make -C osdep
make[2](1]:): Entering directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src/osdep'
Building for Linux
make[Entering directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src/osdep'
gcc -g -W -Wall -Werror -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -Werror -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -Werror -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -fPIC -I..    -c -o linux.o linux.c
cc1: warnings being treated as errors
linux.c: In function is_ndiswrapper:
linux.c:164: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_rate:
linux.c:355: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_channel:
linux.c:729: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:751: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:767: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function linux_set_freq:
linux.c:820: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function set_monitor:
linux.c:941: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:961: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:980: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:997: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1035: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1043: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1051: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c: In function do_linux_open:
linux.c:1425: error: ignoring return value of system, declared with attribute warn_unused_result
linux.c:1474: error: ignoring return value of system, declared with attribute warn_unused_result
linux.c:1495: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1521: error: ignoring return value of chdir, declared with attribute warn_unused_result
linux.c:1539: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1553: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1598: error: ignoring return value of fgets, declared with attribute warn_unused_result
linux.c:1627: error: ignoring return value of fgets, declared with attribute warn_unused_result
make[3](3]:): *** [Error 1
make[3](linux.o]): Leaving directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src/osdep'
make[*** [all](2]:) Error 2
make[Leaving directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src/osdep'
make[1](2]:): *** [Error 2
make[1](osd]): Leaving directory `/home/ea/Desktop/aircrack-ng-1.0-rc1/src'
make: *** [all] Error 2
ea@nbea:~/Desktop/aircrack-ng-1.0-rc1$

**Comment by aircrack-ng** [comment]
**Comment by anonymous on 16 Dec 2008 06:33 UTC**

That is fixed in svn. Try svn trunk and report back.

**Comment by aircrack-ng** [comment]
**Comment by d bitmus on 16 Dec 2008 06:33 UTC**


succesfull.
thanks.

**Comment by aircrack-ng** [comment]
**Modified by misterx on 16 Dec 2008 06:33 UTC**
