### ISSUE TITLE
implicit declaration of functions __cpuid, __cpuid_count, __get_cpuid_max

### ISSUE THREAD

**Issue by aircrack-ng** [aircrack-ng/aircrack-ng#1717]
**Reported by Ryan Schmidt  aircrack ng on 18 Jan 2017 11:57 UTC**

1.2-rc4 builds fine on OS X 10.8 Mountain Lion and later, but fails to compile on OS X 10.7 Lion:

https://build.macports.org/builders/ports-10.7_x86_64_legacy-builder/builds/22537/steps/install-port/logs/stdio

```
cpuid.c:104:27: warning: implicit declaration of function '__get_cpuid_max' is invalid in C99 [       unsigned int max_level = __get_cpuid_max(0, NULL);
                                 ^
cpuid.c:107:3: warning: implicit declaration of function '__cpuid_count' is invalid in C99 [-Wimplicit-function-declaration](-Wimplicit-function-declaration]
)
                __cpuid_count(7, 0, eax, ebx, ecx, edx);
                ^
cpuid.c:120:2: warning: implicit declaration of function '__cpuid' is invalid in C99 [       __cpuid(1, eax, ebx, ecx, edx);
        ^
```

```
Undefined symbols for architecture x86_64:
  "___cpuid", referenced from:
      _cpuid_simdsize in cpuid.o
      _cpuid_vendor in cpuid.o
      _cpuid_featureflags in cpuid.o
      _cpuid_modelinfo in cpuid.o
      _cpuid_getinfo in cpuid.o
  "___cpuid_count", referenced from:
      _cpuid_simdsize in cpuid.o
      _cpuid_featureflags in cpuid.o
      _cpuid_getinfo in cpuid.o
  "___get_cpuid_max", referenced from:
      _cpuid_simdsize in cpuid.o
      _cpuid_featureflags in cpuid.o
      _cpuid_getinfo in cpuid.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

On Mac OS X 10.6 Snow Leopard, the error is:

https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/18170/steps/install-port/logs/stdio

```
cpuid.c:29:20: error: cpuid.h: No such file or directory
```

```
cpuid.c: In function cpuid_simdsize:
cpuid.c:104: warning: implicit declaration of function __get_cpuid_max
cpuid.c:107: warning: implicit declaration of function __cpuid_count
cpuid.c:120: warning: implicit declaration of function __cpuid
<builtin>: recipe for target 'cpuid.o' failed
gmake[1](-Wimplicit-function-declaration]
): *** [cpuid.o] Error 1
```

**Comment by aircrack-ng** [comment]
**Comment by misterx on 18 Jan 2017 11:57 UTC**

OSX 10.6 and 10.7 are not supported anymore so unless you have a patch for both of those, there isn't much I can do (plus I don't have access to any Mac running those versions).

Feel free to reopen the ticket if you have a patch or can give me access to machines running those versions.

**Comment by ryandesign** [comment]
I worked around this problem in MacPorts by having aircrack-ng build using a newer clang compiler on 10.7.
